In [136]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

'건강보조식품 소매업', '골프장 운영업', '과실 및 채소 소매업', '관광 민예품 및 선물용품 소매업',
       '그외 기타 스포츠시설 운영업', '그외 기타 종합 소매업', '기타 대형 종합 소매업', '기타 외국식 음식점업',
       '기타 주점업', '기타음식료품위주종합소매업', '마사지업', '비알콜 음료점업', '빵 및 과자류 소매업',
       '서양식 음식점업', '수산물 소매업', '슈퍼마켓', '스포츠 및 레크레이션 용품 임대업', '여관업', '욕탕업',
       '육류 소매업', '일반유흥 주점업', '일식 음식점업', '전시 및 행사 대행업', '중식 음식점업',
       '차량용 가스 충전업', '차량용 주유소 운영업', '체인화 편의점', '피자 햄버거 샌드위치 및 유사 음식점업',
       '한식 음식점업', '호텔업', '화장품 및 방향제 소매업', '휴양콘도 운영업', '여행사업', '자동차 임대업',
       '면세점', '버스 운송업', '택시 운송업', '기타 수상오락 서비스업', '내항 여객 운송업',
       '그외 기타 분류안된 오락관련 서비스업', '정기 항공 운송업'

## ADV data

In [137]:
ad_data = pd.read_csv("data/당월대비_익월_매체별_업종별_광고경기전망지수_20200712161649.csv", encoding="CP949")
ad_data.head()

,업종별(1),2019. 01,2019. 01.1,2019. 01.2,2019. 01.3,2019. 01.4,2019. 01.5,2019. 01.6,2019. 02,2019. 02.1,...,2020. 03.4,2020. 03.5,2020. 03.6,2020. 04,2020. 04.1,2020. 04.2,2020. 04.3,2020. 04.4,2020. 04.5,2020. 04.6
0,업종별(1),종합,지상파TV,케이블TV,종합편성TV,라디오,신문,온라인-모바일,종합,지상파TV,...,라디오,신문,온라인-모바일,종합,지상파TV,케이블TV,종합편성TV,라디오,신문,온라인-모바일
1,종합,97.6,93.6,94.3,94.1,92.5,91.9,107.9,104.6,95.6,...,99.8,108.3,114.3,105.7,102.6,102.2,100.7,98.5,98.9,108.5
2,가정용품 및 가사서비스,91.7,86.1,86.1,88.9,86.1,83.3,105.6,91.4,77.1,...,118.2,109.1,136.4,130.0,110.0,130.0,120.0,100.0,100.0,130.0
3,교육 및 사회복지서비스,105.9,97.1,108.8,100.0,97.1,94.1,117.6,88.6,94.3,...,86.7,103.3,96.7,98.2,96.5,98.2,94.7,100.0,98.2,108.8
4,금융 및 보험서비스,92.3,88.5,92.3,84.6,84.6,73.1,100.0,107.4,92.6,...,100.0,120.6,117.6,113.5,110.8,110.8,105.4,100.0,105.4,108.1

In [138]:
date = []

for i in ["2019", "2020"]:
    for j in range(1,13):
        if j < 10:
            temp = i + ". 0" + str(j)
            date.append(temp)
            if (i=="2020") & (j==4):
                break
        else:
            temp = i + ". " + str(j)
            date.append(temp)

In [139]:
data = pd.DataFrame(ad_data.loc[1, date])
data.index = pd.to_datetime(data.index)
data.rename(columns={1:"adv_data"}, inplace=True)

In [140]:
data

           adv_data
2019-01-01     97.6
2019-02-01    104.6
2019-03-01    114.2
2019-04-01    116.2
2019-05-01    112.5
2019-06-01     97.8
2019-07-01    102.0
2019-08-01    104.2
2019-09-01    116.3
2019-10-01    102.4
2019-11-01     99.3
2019-12-01    102.9
2020-01-01     99.8
2020-02-01    100.7
2020-03-01    111.1
2020-04-01    105.7

## GDP data

In [141]:
gdp_data = pd.read_csv("data/경제활동별_GDP_및_GNI_원계열__실질__분기_및_연간__20200712154907.csv", encoding="CP949")
gdp_data

,"경제활동별 GDP 및 GNI(원계열, 실질, 분기 및 연간)별",2019 1/4,2019 2/4,2019 3/4,2019 4/4,2020 1/4
0,농림어업,6221.5,8159.0,8322.0,10156.7,6197.8
1,재배업,3723.6,5140.2,5293.4,6338.1,3744.4
2,축산업,1568.0,1726.2,1725.6,2218.6,1623.4
3,임업,211.1,690.0,682.5,833.9,219.3
4,어업,674.7,567.4,576.2,730.6,630.9
5,광업,411.8,524.5,451.3,480.0,420.2
6,제조업,113265.5,120836.2,124058.6,131452.4,117204.1
7,음식료품 제조업,5391.4,5655.9,5343.7,5873.9,5513.7
8,섬유 및 가죽제품 제조업,3862.9,3418.2,3194.7,3545.6,3781.2
9,"목재, 종이, 인쇄 및 복제업",3094.5,3350.0,3221.3,3843.3,3129.4
10,코크스 및 석유정제품 제조업,3710.6,3530.9,3366.7,3424.4,3466.2
11,화학물질 및 화학제품 제조업,18048.6,18677.7,19213.1,19467.5,18124.1
12,비금속광물제품 제조업,3062.3,3481.1,3465.2,3811.3,2958.6
13,1차금속 제조업,6443.8,6736.0,6626.3,6840.2,6341.5
14,금속가공제품 제조업,8822.1,7251.3,8154.0,10560.8,8652.8
15,"컴퓨터, 전자 및 광학기기 제조업",28868.0,33940.2,38583.4,37855.4,32740.2
16,전기장비 제조업,7181.1,7645.8,7299.6,7315.2,7238.4
17,기계 및 장비 제조업,9958.0,10415.2,10485.8,11202.7,10306.0
18,운송장비 제조업,11952.9,13602.9,11899.1,14143.6,11575.2
19,기타 제조업 및 산업용 장비 수리업,2694.5,2694.0,2359.0,2976.3,2727.0
20,"전기, 가스 및 수도사업",12437.0,12049.0,9634.0,10801.8,13329.0
21,전기업,8185.8,8243.6,6580.9,6004.7,9149.4
22,"가스, 증기 및 공기조절 공급업",2620.8,1548.3,1276.8,2080.6,2555.7
23,"수도, 하수 및 폐기물 처리, 원료 재생업",2060.8,2432.2,1926.7,2467.0,2198.2
24,건설업,17063.3,24409.7,22281.6,25729.6,17569.7
25,건물건설업,12178.9,15889.8,14924.0,15716.4,11659.8
26,주거용 건물건설업,6660.4,8061.2,7376.8,7484.5,5955.4
27,비주거용 건물건설업,5516.8,7830.3,7549.9,8236.5,5705.6
28,토목건설업,2033.6,3668.2,2850.9,4299.8,2502.0
29,전문건설업,2852.4,4850.6,4506.0,5710.1,3408.2
30,서비스업,254291.3,258040.3,258181.0,269391.3,254753.0
31,도소매 및 숙박음식업,42137.7,43352.4,42615.8,46314.0,40393.3
32,도소매업,32804.7,33345.2,32465.8,35497.5,32455.4
33,숙박 및 음식점업,9361.5,10009.4,10131.2,10810.5,8100.3
34,운수업,14786.6,15484.4,16012.8,16463.2,13276.3
35,금융 및 보험업,25661.7,26091.1,26031.8,25601.6,27230.0
36,부동산업,33633.4,34381.3,34432.0,34147.2,34140.0
37,정보통신업,20250.7,20177.0,19622.0,22423.6,20968.6
38,통신업,5567.8,5255.7,5146.2,5095.2,5685.6
39,"출판, 방송, 영상, 정보서비스",14713.6,14917.7,14476.4,17237.1,15345.1
40,사업서비스업,34574.8,39916.4,39373.3,43926.3,34978.1
41,"전문, 과학 및 기술관련 서비스업",21904.2,26193.0,25146.1,27093.6,22596.8
42,사업지원 서비스업,12683.2,13705.6,14234.3,16875.1,12369.3
43,"공공행정, 국방 및 사회보장",28721.8,27385.6,25601.2,26510.9,30016.1
44,교육서비스업,23515.8,20086.6,22146.5,21744.7,23048.3
45,"의료, 보건업 및 사회복지서비스업",20573.9,21502.6,20895.3,22075.0,21356.0
46,문화 및 기타 서비스업,10348.9,9617.0,11491.7,10251.5,9179.6
47,"예술, 스포츠 및 여가관련 서비스업",5487.3,4330.2,5949.8,4836.8,4511.9
48,기타 서비스업,4890.8,5273.3,5566.7,5411.9,4674.4
49,총부가가치(기초가격),402909.5,423896.8,423170.5,448281.8,408537.0
50,순생산물세,34361.0,37391.7,39862.3,39197.6,34748.1
51,"국내총생산(시장가격, GDP)",437193.3,461251.3,463085.9,487427.9,443200.4
52,교역조건 변화를 반영한 실질무역손익,-1281.8,-10066.1,-13668.9,-15208.1,-10009.0
53,국내총소득(GDI),435911.5,451185.2,449417.1,472219.8,433191.4
54,국외순수취요소소득,2100.6,-383.4,7154.7,6463.6,4782.0
55,국민총소득(GNI),438021.1,450834.8,456586.5,478694.1,437974.6

In [142]:
# GDP, GDI, GNI 사용

temp = pd.DataFrame(gdp_data.iloc[[51, 53, 55], :])
temp= temp.T.iloc[1:, :].rename(columns={51:"GDP", 53:"GDI", 55:"GNI"})
temp

             GDP     GDI     GNI
2019 1/4  437193  435912  438021
2019 2/4  461251  451185  450835
2019 3/4  463086  449417  456586
2019 4/4  487428  472220  478694
2020 1/4  443200  433191  437975

In [143]:
data["GDP"] = [temp.GDP.iloc[0]]*4 + [temp.GDP.iloc[1]]*4 + [temp.GDP.iloc[2]]*4 + [temp.GDP.iloc[3]]*4
data["GDI"] = [temp.GDI.iloc[0]]*4 + [temp.GDI.iloc[1]]*4 + [temp.GDI.iloc[2]]*4 + [temp.GDI.iloc[3]]*4
data["GNI"] = [temp.GNI.iloc[0]]*4 + [temp.GNI.iloc[1]]*4 + [temp.GNI.iloc[2]]*4 + [temp.GNI.iloc[3]]*4
data

           adv_data       GDP       GDI       GNI
2019-01-01     97.6  437193.3  435911.5  438021.1
2019-02-01    104.6  437193.3  435911.5  438021.1
2019-03-01    114.2  437193.3  435911.5  438021.1
2019-04-01    116.2  437193.3  435911.5  438021.1
2019-05-01    112.5  461251.3  451185.2  450834.8
2019-06-01     97.8  461251.3  451185.2  450834.8
2019-07-01    102.0  461251.3  451185.2  450834.8
2019-08-01    104.2  461251.3  451185.2  450834.8
2019-09-01    116.3  463085.9  449417.1  456586.5
2019-10-01    102.4  463085.9  449417.1  456586.5
2019-11-01     99.3  463085.9  449417.1  456586.5
2019-12-01    102.9  463085.9  449417.1  456586.5
2020-01-01     99.8  487427.9  472219.8  478694.1
2020-02-01    100.7  487427.9  472219.8  478694.1
2020-03-01    111.1  487427.9  472219.8  478694.1
2020-04-01    105.7  487427.9  472219.8  478694.1

In [144]:
unemployment_data = pd.read_csv("data/행정구역_시도__성별_실업률.csv", encoding="CP949")
unemployment_data

,시도별,성별,2019. 01,2019. 02,2019. 03,2019. 04,2019. 05,2019. 06,2019. 07,2019. 08,2019. 09,2019. 10,2019. 11,2019. 12,2020. 01,2020. 02,2020. 03,2020. 04
0,계,계,4.5,4.7,4.3,4.4,4.0,4.0,3.9,3.0,3.1,3.0,3.1,3.4,4.1,4.1,4.2,4.2
1,계,남자,4.4,4.5,4.4,4.6,4.3,4.2,3.9,3.2,3.4,3.2,3.3,3.3,3.9,4.0,4.2,4.2
2,계,여자,4.5,5.0,4.1,4.1,3.7,3.7,3.7,2.8,2.8,2.8,2.7,3.4,4.4,4.2,4.4,4.2
3,서울특별시,계,5.1,5.3,5.6,5.2,4.9,4.4,4.4,3.8,3.6,3.6,3.4,3.3,4.2,4.3,5.0,5.3
4,서울특별시,남자,5.2,5.1,5.6,5.5,5.4,4.8,4.5,4.2,3.8,3.8,3.9,3.2,3.7,4.1,4.7,5.0
5,서울특별시,여자,5.0,5.6,5.5,4.9,4.2,3.8,4.2,3.5,3.4,3.3,2.9,3.5,4.8,4.4,5.4,5.8
6,부산광역시,계,4.4,4.9,5.1,4.6,3.9,4.1,3.5,2.1,3.3,2.9,3.1,3.1,3.8,4.3,4.3,5.0
7,부산광역시,남자,4.0,4.6,5.3,5.0,4.0,4.3,3.3,1.6,3.4,2.9,3.3,3.3,3.5,4.4,4.5,5.4
8,부산광역시,여자,4.8,5.2,5.0,4.1,3.7,3.7,3.7,2.8,3.0,3.0,2.9,2.9,4.2,4.2,3.9,4.5
9,대구광역시,계,3.7,4.3,4.4,4.6,4.3,4.1,4.2,3.3,3.1,3.0,2.7,2.6,3.6,4.0,4.2,4.1
10,대구광역시,남자,4.0,4.3,4.7,4.9,4.7,4.2,4.2,3.3,3.1,3.3,2.9,2.5,3.5,4.0,4.5,4.6
11,대구광역시,여자,3.4,4.3,3.9,4.3,3.9,4.0,4.3,3.3,3.1,2.7,2.5,2.8,3.8,3.9,3.8,3.4
12,인천광역시,계,4.5,5.4,4.8,4.9,4.1,4.7,4.9,3.8,3.5,3.8,3.9,3.8,4.5,4.2,5.1,4.9
13,인천광역시,남자,4.9,5.4,5.1,4.8,4.0,4.9,4.6,3.6,3.4,4.0,4.1,3.7,4.1,3.8,4.7,4.6
14,인천광역시,여자,4.0,5.3,4.4,5.1,4.2,4.5,5.2,4.2,3.7,3.7,3.6,3.9,5.0,4.7,5.7,5.3
15,광주광역시,계,4.9,5.3,4.1,4.5,4.0,3.5,3.3,3.2,3.4,2.7,2.8,2.8,3.8,3.4,3.8,4.2
16,광주광역시,남자,4.8,5.0,4.2,5.0,3.9,3.1,3.0,2.5,3.1,2.9,2.6,2.4,3.9,3.7,4.4,4.5
17,광주광역시,여자,5.0,5.7,3.8,3.7,4.2,4.1,3.7,4.1,3.9,2.5,3.0,3.4,3.7,3.1,3.1,3.7
18,대전광역시,계,5.8,5.4,4.7,5.2,4.6,4.6,3.7,2.8,2.9,3.2,3.5,4.2,5.1,5.0,5.1,5.1
19,대전광역시,남자,5.7,5.4,4.6,5.4,4.4,4.5,4.6,3.1,3.6,3.8,4.2,4.4,5.3,5.4,5.1,5.2
20,대전광역시,여자,6.1,5.4,4.8,5.0,4.9,4.7,2.4,2.3,2.0,2.4,2.6,4.0,4.9,4.4,5.1,4.9
21,울산광역시,계,5.4,5.3,5.2,5.2,4.5,4.0,3.8,3.1,3.6,3.1,3.6,3.5,5.2,5.3,4.4,4.2
22,울산광역시,남자,6.3,5.6,5.4,5.3,4.7,4.3,4.2,3.6,3.7,3.1,3.7,3.8,4.9,4.9,3.6,3.9
23,울산광역시,여자,3.9,4.6,4.8,5.0,4.1,3.5,3.1,2.3,3.6,3.3,3.4,3.0,5.7,5.9,5.8,4.7
24,세종특별자치시,계,2.6,3.5,2.0,1.8,2.6,2.8,2.9,2.2,2.4,2.6,3.2,3.6,2.7,3.4,3.0,3.1
25,세종특별자치시,남자,1.7,2.9,2.1,2.0,1.9,2.2,2.7,1.8,1.9,2.8,2.8,3.8,2.6,3.7,3.3,3.4
26,세종특별자치시,여자,3.9,4.5,2.0,1.6,3.6,3.7,3.3,2.7,3.2,2.4,3.6,3.2,2.8,3.0,2.6,2.6
27,경기도,계,4.4,4.6,3.9,4.2,4.0,3.8,3.9,3.2,3.4,3.1,3.4,3.7,4.0,4.3,4.2,4.0
28,경기도,남자,4.5,4.3,4.0,4.3,3.9,3.8,3.8,3.4,3.8,3.5,3.9,4.2,4.4,4.5,4.0,4.0
29,경기도,여자,4.2,4.9,3.9,4.1,4.2,3.8,4.0,2.7,2.8,2.7,2.8,3.0,3.5,4.2,4.4,4.0
30,강원도,계,6.5,6.7,3.7,3.5,3.1,3.4,2.3,2.2,2.3,2.7,2.4,4.9,6.9,4.7,3.7,3.9
31,강원도,남자,4.7,5.2,4.2,3.6,3.7,3.9,2.6,2.5,2.6,2.6,2.3,4.1,5.9,5.2,3.8,3.8
32,강원도,여자,8.8,8.5,3.2,3.2,2.3,2.8,1.9,1.7,1.9,2.8,2.5,5.9,8.2,4.1,3.6,4.1
33,충청북도,계,3.0,4.0,3.0,3.7,3.6,3.7,3.3,2.2,2.0,1.9,2.5,3.7,4.2,3.7,3.2,2.9
34,충청북도,남자,2.8,4.0,3.4,3.8,4.2,4.5,3.4,2.5,2.3,2.2,3.0,3.7,3.9,3.0,3.4,3.0
35,충청북도,여자,3.4,3.9,2.6,3.6,2.8,2.6,3.1,2.0,1.6,1.6,2.0,3.6,4.6,4.7,2.9,2.8
36,충청남도,계,3.0,3.1,2.7,3.2,3.0,3.5,3.4,2.8,3.0,2.4,2.0,2.3,3.5,4.2,3.9,3.5
37,충청남도,남자,2.5,2.6,2.4,3.1,2.8,3.0,3.2,2.9,3.1,2.3,1.8,1.8,2.8,3.3,3.7,3.1
38,충청남도,여자,3.7,4.0,3.3,3.2,3.3,4.1,3.8,2.8,2.9,2.5,2.2,3.1,4.4,5.5,4.3,4.1
39,전라북도,계,3.8,3.2,3.0,3.0,2.4,2.6,2.5,2.4,2.4,2.9,2.1,2.1,2.7,2.9,2.7,2.6
40,전라북도,남자,3.7,3.2,3.7,3.7,2.7,2.8,2.7,2.9,2.8,3.4,2.9,2.1,2.4,2.7,3.2,3.4
41,전라북도,여자,3.9,3.3,2.1,2.0,2.0,2.2,2.1,1.7,1.9,2.4,1.1,2.0,3.0,3.1,2.1,1.5
42,전라남도,계,2.3,3.2,3.0,3.3,3.0,3.8,3.4,1.9,1.8,1.4,1.5,2.0,3.7,3.0,2.6,2.5
43,전라남도,남자,1.9,2.6,3.8,3.9,3.3,3.9,3.6,1.9,1.8,1.4,1.7,2.0,3.3,2.9,2.5,2.6
44,전라남도,여자,2.8,4.0,1.9,2.5,2.7,3.6,3.1,1.8,1.9,1.5,1.3,1.9,4.3,3.2,2.6,2.3
45,경상북도,계,5.6,5.1,4.1,4.9,4.1,4.4,3.3,2.7,3.0,3.0,2.5,4.3,5.2,3.8,3.7,4.1
46,경상북도,남자,5.0,5.3,4.2,5.5,5.0,5.2,4.2,3.3,3.7,3.7,2.9,3.9,4.8,3.9,3.7,4.6
47,경상북도,여자,6.6,4.7,3.9,4.0,2.9,3.3,2.0,1.9,1.9,2.0,2.1,5.0,5.7,3.7,3.7,3.4
48,경상남도,계,4.2,4.7,4.2,4.7,4.1,4.6,4.7,2.8,2.7,2.9,2.9,2.7,3.6,3.9,4.7,3.9
49,경상남도,남자,4.4,5.0,4.6,5.0,4.9,4.8,4.8,2.8,2.7,2.3,2.5,2.2,3.0,3.3,4.7,4.0
50,경상남도,여자,3.9,4.3,3.5,4.2,3.1,4.2,4.7,2.9,2.8,3.9,3.6,3.4,4.4,4.6,4.8,3.8
51,제주도,계,2.8,2.8,2.1,2.6,2.4,1.9,2.4,1.5,1.6,1.6,1.6,2.2,2.7,2.7,2.8,2.6
52,제주도,남자,2.2,2.9,2.1,2.5,2.5,1.8,2.5,2.2,2.7,1.9,1.6,1.4,1.7,2.1,3.2,3.4
53,제주도,여자,3.5,2.6,2.1,2.9,2.3,2.0,2.3,0.7,0.4,1.3,1.6,3.0,3.8,3.3,2.4,1.5

In [145]:
data["unemployment_rate"] = unemployment_data.iloc[0, 2:]
data

           adv_data       GDP       GDI       GNI unemployment_rate
2019-01-01     97.6  437193.3  435911.5  438021.1               4.5
2019-02-01    104.6  437193.3  435911.5  438021.1               4.7
2019-03-01    114.2  437193.3  435911.5  438021.1               4.3
2019-04-01    116.2  437193.3  435911.5  438021.1               4.4
2019-05-01    112.5  461251.3  451185.2  450834.8                 4
2019-06-01     97.8  461251.3  451185.2  450834.8                 4
2019-07-01    102.0  461251.3  451185.2  450834.8               3.9
2019-08-01    104.2  461251.3  451185.2  450834.8                 3
2019-09-01    116.3  463085.9  449417.1  456586.5               3.1
2019-10-01    102.4  463085.9  449417.1  456586.5                 3
2019-11-01     99.3  463085.9  449417.1  456586.5               3.1
2019-12-01    102.9  463085.9  449417.1  456586.5               3.4
2020-01-01     99.8  487427.9  472219.8  478694.1               4.1
2020-02-01    100.7  487427.9  472219.8  478694.1               4.1
2020-03-01    111.1  487427.9  472219.8  478694.1               4.2
2020-04-01    105.7  487427.9  472219.8  478694.1               4.2

In [146]:
unemployment_data["시도별"] = unemployment_data["시도별"].map({"계":"계", 
                            "서울특별시":"서울", "부산광역시":"부산", "대구광역시":"대구",
                            "인천광역시":"인천", "광주광역시":"광주", "대전광역시":"대전",
                            "울산광역시":"울산", "세종특별자치시":"세종", "경기도":"경기",
                            "강원도":"강원", "충청북도":"충북", "충청남도":"충남",
                            "전라북도":"전북", "전라남도":"전남", "경상북도":"경북",
                            "경상남도":"경남", "제주도":"제주"})

In [147]:
unemployment_data.T

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,53
시도별,계,계,계,서울,서울,서울,부산,부산,부산,대구,...,전남,경북,경북,경북,경남,경남,경남,제주,제주,제주
성별,계,남자,여자,계,남자,여자,계,남자,여자,계,...,여자,계,남자,여자,계,남자,여자,계,남자,여자
2019. 01,4.5,4.4,4.5,5.1,5.2,5,4.4,4,4.8,3.7,...,2.8,5.6,5,6.6,4.2,4.4,3.9,2.8,2.2,3.5
2019. 02,4.7,4.5,5,5.3,5.1,5.6,4.9,4.6,5.2,4.3,...,4,5.1,5.3,4.7,4.7,5,4.3,2.8,2.9,2.6
2019. 03,4.3,4.4,4.1,5.6,5.6,5.5,5.1,5.3,5,4.4,...,1.9,4.1,4.2,3.9,4.2,4.6,3.5,2.1,2.1,2.1
2019. 04,4.4,4.6,4.1,5.2,5.5,4.9,4.6,5,4.1,4.6,...,2.5,4.9,5.5,4,4.7,5,4.2,2.6,2.5,2.9
2019. 05,4,4.3,3.7,4.9,5.4,4.2,3.9,4,3.7,4.3,...,2.7,4.1,5,2.9,4.1,4.9,3.1,2.4,2.5,2.3
2019. 06,4,4.2,3.7,4.4,4.8,3.8,4.1,4.3,3.7,4.1,...,3.6,4.4,5.2,3.3,4.6,4.8,4.2,1.9,1.8,2
2019. 07,3.9,3.9,3.7,4.4,4.5,4.2,3.5,3.3,3.7,4.2,...,3.1,3.3,4.2,2,4.7,4.8,4.7,2.4,2.5,2.3
2019. 08,3,3.2,2.8,3.8,4.2,3.5,2.1,1.6,2.8,3.3,...,1.8,2.7,3.3,1.9,2.8,2.8,2.9,1.5,2.2,0.7
2019. 09,3.1,3.4,2.8,3.6,3.8,3.4,3.3,3.4,3,3.1,...,1.9,3,3.7,1.9,2.7,2.7,2.8,1.6,2.7,0.4
2019. 10,3,3.2,2.8,3.6,3.8,3.3,2.9,2.9,3,3,...,1.5,3,3.7,2,2.9,2.3,3.9,1.6,1.9,1.3
2019. 11,3.1,3.3,2.7,3.4,3.9,2.9,3.1,3.3,2.9,2.7,...,1.3,2.5,2.9,2.1,2.9,2.5,3.6,1.6,1.6,1.6
2019. 12,3.4,3.3,3.4,3.3,3.2,3.5,3.1,3.3,2.9,2.6,...,1.9,4.3,3.9,5,2.7,2.2,3.4,2.2,1.4,3
2020. 01,4.1,3.9,4.4,4.2,3.7,4.8,3.8,3.5,4.2,3.6,...,4.3,5.2,4.8,5.7,3.6,3,4.4,2.7,1.7,3.8
2020. 02,4.1,4,4.2,4.3,4.1,4.4,4.3,4.4,4.2,4,...,3.2,3.8,3.9,3.7,3.9,3.3,4.6,2.7,2.1,3.3
2020. 03,4.2,4.2,4.4,5,4.7,5.4,4.3,4.5,3.9,4.2,...,2.6,3.7,3.7,3.7,4.7,4.7,4.8,2.8,3.2,2.4
2020. 04,4.2,4.2,4.2,5.3,5,5.8,5,5.4,4.5,4.1,...,2.3,4.1,4.6,3.4,3.9,4,3.8,2.6,3.4,1.5

In [148]:
# 나중에 하기

In [149]:
len(data)

16

## 소비자경향지수(CSI)

In [150]:
csi_data = ["97.5", "99.5", "99.8", "101.6", "97.9", "97.5", 
            "95.9", "92.5", "96.9", "98.6",  "101.0", "100.5", 
            "104.2", "96.9", "78.4", "70.8"]
data["CSI"] = csi_data

In [151]:
data

           adv_data       GDP       GDI       GNI unemployment_rate    CSI
2019-01-01     97.6  437193.3  435911.5  438021.1               4.5   97.5
2019-02-01    104.6  437193.3  435911.5  438021.1               4.7   99.5
2019-03-01    114.2  437193.3  435911.5  438021.1               4.3   99.8
2019-04-01    116.2  437193.3  435911.5  438021.1               4.4  101.6
2019-05-01    112.5  461251.3  451185.2  450834.8                 4   97.9
2019-06-01     97.8  461251.3  451185.2  450834.8                 4   97.5
2019-07-01    102.0  461251.3  451185.2  450834.8               3.9   95.9
2019-08-01    104.2  461251.3  451185.2  450834.8                 3   92.5
2019-09-01    116.3  463085.9  449417.1  456586.5               3.1   96.9
2019-10-01    102.4  463085.9  449417.1  456586.5                 3   98.6
2019-11-01     99.3  463085.9  449417.1  456586.5               3.1  101.0
2019-12-01    102.9  463085.9  449417.1  456586.5               3.4  100.5
2020-01-01     99.8  487427.9  472219.8  478694.1               4.1  104.2
2020-02-01    100.7  487427.9  472219.8  478694.1               4.1   96.9
2020-03-01    111.1  487427.9  472219.8  478694.1               4.2   78.4
2020-04-01    105.7  487427.9  472219.8  478694.1               4.2   70.8

## 소비자동향조사 전국

In [160]:
consumer = pd.read_csv("data/소비자동향조사_전국__20200712155818.csv", encoding="CP949")
consumer

# 소비자심리지수 = CSI

,지수코드별,분류코드별,2019. 01,2019. 02,2019. 03,2019. 04,2019. 05,2019. 06,2019. 07,2019. 08,2019. 09,2019. 10,2019. 11,2019. 12,2020. 01,2020. 02,2020. 03,2020. 04
0,현재생활형편CSI,전체,90,93,91,93,91,91,91,90,92,92,92,92,93,91,83,77
1,현재생활형편CSI,남자,90,93,91,92,91,91,90,89,92,91,92,91,93,91,82,76
2,현재생활형편CSI,여자,90,93,93,96,92,95,94,93,92,93,93,94,95,94,84,79
3,현재생활형편CSI,40세미만,93,99,97,98,95,95,95,95,97,96,95,96,97,96,90,87
4,현재생활형편CSI,40-50세,93,95,91,95,93,92,93,92,94,94,95,94,96,96,85,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524,임금수준전망CSI,임차 등,120,119,115,115,114,114,115,117,115,114,114,115,116,114,106,99
525,임금수준전망CSI,서울,122,121,115,115,116,117,119,117,117,117,117,116,120,115,109,99
526,임금수준전망CSI,6대광역시,124,120,117,118,117,118,119,121,119,118,117,117,121,118,111,104
527,임금수준전망CSI,기타도시,122,120,117,116,115,116,117,117,116,117,116,117,118,116,109,101
528,소비자심리지수,전체,98,100,100,102,98,98,96,92,97,99,101,101,104,97,78,71

In [ ]:

consumer.iloc[-1:, 2:]