In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [43]:
data = pd.read_csv("../Data/Biometric Data Analysis/train.csv").fillna(-999)

In [44]:
data.rho.unique()
data.drop("id", axis=1, inplace=True)

In [45]:
# group by rho

data_rho_25 = data[data['rho'] == 25]
data_rho_20 = data[data['rho'] == 20]
data_rho_15 = data[data['rho'] == 15]
data_rho_10 = data[data['rho'] == 10]

### XG Boost

In [46]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

In [47]:
def XY(df):
    X = df.iloc[:,:-4]
    y_hhb = df.iloc[:,-4]
    y_hhbo2 = df.iloc[:,-3]
    y_ca = df.iloc[:,-2]
    y_na = df.iloc[:,-1]
    
    return X, y_hhb, y_hhbo2, y_ca, y_na

In [50]:
def XG_Boost(df, num):
    X, y_hhb, y_hhbo2, y_ca, y_na = XY(df)
    
    # Split data
    X1_train, X1_test, y1_train, y1_test = train_test_split(X, y_hhb, test_size=0.2, shuffle=1234)
    X2_train, X2_test, y2_train, y2_test = train_test_split(X, y_hhbo2, test_size=0.2, shuffle=1234)
    X3_train, X3_test, y3_train, y3_test = train_test_split(X, y_ca, test_size=0.2, shuffle=1234)
    X4_train, X4_test, y4_train, y4_test = train_test_split(X, y_na, test_size=0.2, shuffle=1234)
    
    
    xg_reg_hbb = xgb.XGBRegressor(colsample_bytree=0.4603, gamma=0.0468, 
                             learning_rate=0.05, max_depth=3, 
                             min_child_weight=1.7817, n_estimators=2200,
                             reg_alpha=0.4640, reg_lambda=0.8571,
                             subsample=0.5213, silent=1,
                             random_state =7, nthread = -1)
    xg_reg_hbo2 = xgb.XGBRegressor(colsample_bytree=0.4603, gamma=0.0468, 
                             learning_rate=0.05, max_depth=3, 
                             min_child_weight=1.7817, n_estimators=2200,
                             reg_alpha=0.4640, reg_lambda=0.8571,
                             subsample=0.5213, silent=1,
                             random_state =7, nthread = -1)
    xg_reg_ca = xgb.XGBRegressor(colsample_bytree=0.4603, gamma=0.0468, 
                             learning_rate=0.05, max_depth=3, 
                             min_child_weight=1.7817, n_estimators=2200,
                             reg_alpha=0.4640, reg_lambda=0.8571,
                             subsample=0.5213, silent=1,
                             random_state =7, nthread = -1)
    xg_reg_na = xgb.XGBRegressor(colsample_bytree=0.4603, gamma=0.0468, 
                             learning_rate=0.05, max_depth=3, 
                             min_child_weight=1.7817, n_estimators=2200,
                             reg_alpha=0.4640, reg_lambda=0.8571,
                             subsample=0.5213, silent=1,
                             random_state =7, nthread = -1)
    
    
    xg_reg_hbb.fit(X1_train,y1_train)
    preds_hbb = xg_reg_hbb.predict(X1_test)

    xg_reg_hbo2.fit(X2_train,y2_train)
    preds_hbo2 = xg_reg_hbo2.predict(X2_test)

    xg_reg_ca.fit(X3_train,y3_train)
    preds_ca = xg_reg_ca.predict(X3_test)

    xg_reg_na.fit(X4_train,y4_train)
    preds_na = xg_reg_na.predict(X4_test)
    
    
    rmse_hbb = np.sqrt(mean_squared_error(y1_test, preds_hbb))
    rmse_hbo2 = np.sqrt(mean_squared_error(y2_test, preds_hbo2))
    rmse_ca = np.sqrt(mean_squared_error(y3_test, preds_ca))
    rmse_na = np.sqrt(mean_squared_error(y4_test, preds_na))

    print(num, " mm")
    print("RMSE - hbb  : %f" % (rmse_hbb))
    print("RMSE - hbo2 : %f" % (rmse_hbo2))
    print("RMSE - ca   : %f" % (rmse_ca))
    print("RMSE - na   : %f" % (rmse_na))
    
    
    return xg_reg_hbb, xg_reg_hbo2, xg_reg_ca, xg_reg_na

In [51]:
# data_rho_25, data_rho_20, data_rho_15, data_rho_10

hbb_25, hbo2_25, ca_25, na_25 = XG_Boost(data_rho_25, 25)

hbb_20, hbo2_20, ca_20, na_20 = XG_Boost(data_rho_20, 20)

hbb_15, hbo2_15, ca_15, na_15 = XG_Boost(data_rho_15, 15)

hbb_10, hbo2_10, ca_10, na_10 = XG_Boost(data_rho_10, 10)

25  mm
RMSE - hbb  : 1.288123
RMSE - hbo2 : 0.826250
RMSE - ca   : 2.627238
RMSE - na   : 1.961008
20  mm
RMSE - hbb  : 1.299025
RMSE - hbo2 : 0.861177
RMSE - ca   : 2.595377
RMSE - na   : 1.948703
15  mm
RMSE - hbb  : 1.313513
RMSE - hbo2 : 0.878684
RMSE - ca   : 2.623263
RMSE - na   : 1.678088
10  mm
RMSE - hbb  : 1.270361
RMSE - hbo2 : 0.826330
RMSE - ca   : 2.382056
RMSE - na   : 1.422890

In [52]:
test = pd.read_csv("../Data/Biometric Data Analysis/test.csv").fillna(-999)

In [53]:
test_rho_25 = test[test['rho'] == 25]
test_rho_20 = test[test['rho'] == 20]
test_rho_15 = test[test['rho'] == 15]
test_rho_10 = test[test['rho'] == 10]

In [54]:
test_rho_25.head()

,id,rho,650_src,660_src,670_src,680_src,690_src,700_src,710_src,720_src,...,900_dst,910_dst,920_dst,930_dst,940_dst,950_dst,960_dst,970_dst,980_dst,990_dst
4,10004,25,0.00253,0.00757,0.01649,0.00128,0.00000,0.00000,0.00105,0.01975,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.732057e-17,4.110605e-17,0.000000e+00,0.000000e+00,1.910775e-16,2.215673e-15
7,10007,25,0.02086,0.01274,0.00564,0.02591,0.02021,0.03552,0.04008,0.08058,...,-9.990000e+02,-9.990000e+02,1.179564e-18,3.953631e-19,3.859850e-20,8.408864e-19,1.776008e-20,2.324328e-19,7.958847e-19,1.578751e-17
9,10009,25,0.02078,0.02109,0.03051,0.03936,0.04283,0.03698,0.04585,0.03145,...,1.916856e-18,-9.990000e+02,5.892738e-18,3.100210e-18,2.826076e-18,1.850818e-18,2.246850e-18,7.996434e-19,8.171193e-18,5.091564e-17
20,10020,25,0.01464,0.04451,0.08738,0.13294,0.20736,0.29773,0.41921,0.58363,...,0.000000e+00,3.124124e-19,0.000000e+00,6.877190e-20,-9.990000e+02,0.000000e+00,0.000000e+00,1.873963e-19,-9.990000e+02,-9.990000e+02
23,10023,25,0.04235,0.04854,0.06521,0.11027,0.12912,0.21326,0.25468,0.34638,...,4.755581e-19,-9.990000e+02,5.863937e-19,5.275918e-19,0.000000e+00,-9.990000e+02,8.404945e-19,-9.990000e+02,-9.990000e+02,4.558269e-19

In [55]:
# features: iloc[1:]

In [56]:
test_rho_25.iloc[:, 1:].head()

,rho,650_src,660_src,670_src,680_src,690_src,700_src,710_src,720_src,730_src,...,900_dst,910_dst,920_dst,930_dst,940_dst,950_dst,960_dst,970_dst,980_dst,990_dst
4,25,0.00253,0.00757,0.01649,0.00128,0.00000,0.00000,0.00105,0.01975,0.00000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.732057e-17,4.110605e-17,0.000000e+00,0.000000e+00,1.910775e-16,2.215673e-15
7,25,0.02086,0.01274,0.00564,0.02591,0.02021,0.03552,0.04008,0.08058,0.08955,...,-9.990000e+02,-9.990000e+02,1.179564e-18,3.953631e-19,3.859850e-20,8.408864e-19,1.776008e-20,2.324328e-19,7.958847e-19,1.578751e-17
9,25,0.02078,0.02109,0.03051,0.03936,0.04283,0.03698,0.04585,0.03145,0.06261,...,1.916856e-18,-9.990000e+02,5.892738e-18,3.100210e-18,2.826076e-18,1.850818e-18,2.246850e-18,7.996434e-19,8.171193e-18,5.091564e-17
20,25,0.01464,0.04451,0.08738,0.13294,0.20736,0.29773,0.41921,0.58363,0.76227,...,0.000000e+00,3.124124e-19,0.000000e+00,6.877190e-20,-9.990000e+02,0.000000e+00,0.000000e+00,1.873963e-19,-9.990000e+02,-9.990000e+02
23,25,0.04235,0.04854,0.06521,0.11027,0.12912,0.21326,0.25468,0.34638,0.45072,...,4.755581e-19,-9.990000e+02,5.863937e-19,5.275918e-19,0.000000e+00,-9.990000e+02,8.404945e-19,-9.990000e+02,-9.990000e+02,4.558269e-19

In [57]:
def prediction(hbb, hbo2, ca, na, df):
    
    test = df.iloc[:, 1:]
    
    preds_hbb = hbb.predict(test)
    preds_hbo2 = hbo2.predict(test)
    preds_ca = ca.predict(test)
    preds_na = na.predict(test)
    
    df_1 = df.copy()
    
    df_1['hhb'] = preds_hbb
    df_1['hbo2'] = preds_hbo2
    df_1['ca'] = preds_ca
    df_1['na'] = preds_na
    
    return df_1

In [58]:
# test_rho_25 - hbb_25, hbo2_25, ca_25, na_25
# test_rho_20 - hbb_20, hbo2_20, ca_20, na_20
# test_rho_15 - hbb_15, hbo2_15, ca_15, na_15
# test_rho_10 - hbb_10, hbo2_10, ca_10, na_10

rho_25 = prediction(hbb_25, hbo2_25, ca_25, na_25, test_rho_25)
rho_20 = prediction(hbb_20, hbo2_20, ca_20, na_20, test_rho_20)
rho_15 = prediction(hbb_15, hbo2_15, ca_15, na_15, test_rho_15)
rho_10 = prediction(hbb_10, hbo2_10, ca_10, na_10, test_rho_10)

In [59]:
temp = pd.concat([rho_25, rho_20, rho_15, rho_10]).sort_values('id')
id = temp.id
temp = temp.iloc[:, -4:]

In [60]:
submission = pd.concat([id, temp], axis=1)
submission.to_csv("submission/08.csv")

In [61]:
submission.head()

      id        hhb      hbo2         ca        na
0  10000   8.501743  4.571704   9.686200  3.580117
1  10001   5.594748  4.017135   6.103176  2.598938
2  10002  10.096092  4.741925  10.122812  2.354075
3  10003   8.121866  4.295399   9.602994  3.817358
4  10004   5.626268  3.746332   6.671554  3.774438

10000