In [6]:
import numpy as np
import pandas as pd

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [11]:
path = "../../Data/BigContest/Baseball data/csv file/"

data1 = pd.read_csv(path+"2020빅콘테스트_스포츠투아이_제공데이터_경기_2016.csv", encoding="CP949")
data2 = pd.read_csv(path+"2020빅콘테스트_스포츠투아이_제공데이터_경기_2017.csv", encoding="CP949")
data3 = pd.read_csv(path+"2020빅콘테스트_스포츠투아이_제공데이터_경기_2018.csv", encoding="CP949")
data4 = pd.read_csv(path+"2020빅콘테스트_스포츠투아이_제공데이터_경기_2019.csv", encoding="CP949")

In [15]:
data1.head(30)

             G_ID   GDAY_DS VISIT_KEY HOME_KEY  HEADER_NO GWEEK STADIUM
0   20160401HHLG0  20160401        HH       LG          0     금      잠실
1   20160401HTNC0  20160401        HT       NC          0     금      마산
2   20160401KTSK0  20160401        KT       SK          0     금      문학
3   20160401LTWO0  20160401        LT       WO          0     금      고척
4   20160401OBSS0  20160401        OB       SS          0     금      대구
5   20160402HHLG0  20160402        HH       LG          0     토      잠실
6   20160402HTNC0  20160402        HT       NC          0     토      마산
7   20160402KTSK0  20160402        KT       SK          0     토      문학
8   20160402LTWO0  20160402        LT       WO          0     토      고척
9   20160402OBSS0  20160402        OB       SS          0     토      대구
10  20160403KTSK0  20160403        KT       SK          0     일      문학
11  20160403LTWO0  20160403        LT       WO          0     일      고척
12  20160405LGHT0  20160405        LG       HT          0     화      광주
13  20160405NCOB0  20160405        NC       OB          0     화      잠실
14  20160405SKLT0  20160405        SK       LT          0     화      사직
15  20160405SSKT0  20160405        SS       KT          0     화      수원
16  20160405WOHH0  20160405        WO       HH          0     화      대전
17  20160406NCOB0  20160406        NC       OB          0     수      잠실
18  20160406SKLT0  20160406        SK       LT          0     수      사직
19  20160406SSKT0  20160406        SS       KT          0     수      수원
20  20160406WOHH0  20160406        WO       HH          0     수      대전
21  20160407LGHT0  20160407        LG       HT          0     목      광주
22  20160407NCOB0  20160407        NC       OB          0     목      잠실
23  20160407SKLT0  20160407        SK       LT          0     목      사직
24  20160407SSKT0  20160407        SS       KT          0     목      수원
25  20160407WOHH0  20160407        WO       HH          0     목      대전
26  20160408HHNC0  20160408        HH       NC          0     금      마산
27  20160408HTKT0  20160408        HT       KT          0     금      수원
28  20160408LGSK0  20160408        LG       SK          0     금      문학
29  20160408SSLT0  20160408        SS       LT          0     금      사직