In [13]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import datetime as dt
%matplotlib inline

In [14]:
data = pd.read_csv("data/DP_LIVE_14072020194431101.csv")
# https://data.oecd.org/gdp/real-gdp-forecast.htm#indicator-chart

In [15]:
start = dt.datetime(2019,1,1)
end = dt.datetime(2020,7,1)

In [16]:
gdp_data = pd.DataFrame(index=pd.date_range(start, end, freq='MS'))

In [17]:
def gdp(country):
    temp1 = data[data['LOCATION']==country].Value
    temp2 = [temp1.iloc[0]]*3 + [temp1.iloc[1]]*3 + [temp1.iloc[2]]*3 + [temp1.iloc[3]]*3 + \
            [temp1.iloc[4]]*3 + [temp1.iloc[5]]*3 + [temp1.iloc[6]]*1
    return temp2

In [18]:
for country in data.LOCATION.unique():
    name = country + "_gdp"
    gdp_data[name] = gdp(country)

In [19]:
gdp_data

              JPN_gdp    KOR_gdp    USA_gdp   EA17_gdp   OECD_gdp
2019-01-01   2.540545  -1.351869   3.096140   2.075140   2.584581
2019-02-01   2.540545  -1.351869   3.096140   2.075140   2.584581
2019-03-01   2.540545  -1.351869   3.096140   2.075140   2.584581
2019-04-01   2.122896   4.118698   2.013819   0.408936   1.646587
2019-05-01   2.122896   4.118698   2.013819   0.408936   1.646587
2019-06-01   2.122896   4.118698   2.013819   0.408936   1.646587
2019-07-01   0.009127   1.510299   2.103507   1.223866   1.613839
2019-08-01   0.009127   1.510299   2.103507   1.223866   1.613839
2019-09-01   0.009127   1.510299   2.103507   1.223866   1.613839
2019-10-01  -7.259414   5.350648   2.126630   0.248064   0.626370
2019-11-01  -7.259414   5.350648   2.126630   0.248064   0.626370
2019-12-01  -7.259414   5.350648   2.126630   0.248064   0.626370
2020-01-01  -3.372368  -5.029080  -5.047091 -13.579380  -7.086410
2020-02-01  -3.372368  -5.029080  -5.047091 -13.579380  -7.086410
2020-03-01  -3.372368  -5.029080  -5.047091 -13.579380  -7.086410
2020-04-01 -33.320846 -14.996605 -41.384061 -48.718033 -43.113905
2020-05-01 -33.320846 -14.996605 -41.384061 -48.718033 -43.113905
2020-06-01 -33.320846 -14.996605 -41.384061 -48.718033 -43.113905
2020-07-01  27.016943   9.919523  18.793900  51.373392  29.351269

In [20]:
gdp_data.to_csv("data/world_gdp.csv")